apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'cronjob-metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: cronjob
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: 8080
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'cronjob_.*'
            action: keep
