apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM= # postgres (base64 encoded)
  REDIS_PASSWORD: cmVkaXM= # redis (base64 encoded)
  JWT_SECRET: c2VjcmV0 # secret (base64 encoded)
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  SMTP_USER: eW91ckBnbWFpbC5jb20=
  SMTP_PASS: eW91cl9wYXNzd29yZA==
